### PR TITLE
Convert the last print statements to function call

### PR DESCRIPTION
**Pull request by cavokz**

### CODE REVIEW

**Comment by regebro** [comment]
I believe those tests should fail on Python 3.

**Comment by cavokz** [comment]
At least README.txt is not a test and, being under py3example, I would expect it to be valid Python 3.

test-1.10.txt  is used in "3.9 Optional: Use the iterator-methods on dictionaries", right after the phrase "Remember, if all you want to do is loop over the dictionary, use for x in dict and you will use iterators automatically in both Python 2 and Python 3."

test-4.9.txt is used in "6.2 Coding with context managers" and looks like it should be usable with Python 3.

test-5.2.txt is used in "7.2 Handling exceptions", as part of the "SUPPORTING PYTHON 2 AND 3 WITHOUT 2TO3 CONVERSION", so I would expect to be valid Python 3 code.

I don't know how these files are used in any other context but as far as I can see, my proposal looks appropriate.

**Comment by regebro** [comment]
OK, thanks, I'll take a look.

**Comment by cavokz** [comment]
> OK, thanks, I'll take a look.

Any update on this?

Feel free to close the PR, if you think it's really not needed.

**Pull request closed without merging**
