### PR TITLE
Look for python in different locations

### PR DESCRIPTION
**Pull request by do3cc**
These locations work for me on ubuntu.
So where do I need to sign the CLA?

### CODE REVIEW

**Comment by do3cc** [comment]
Ups, unfinished PR

**Comment by do3cc** [comment]
Now its working
I have three test failures in 3.1 do you have them too and I can fix them or should I investigate if this might be my environment?
@regebro

**Comment by do3cc** [comment]
Forget it, now its working. setuptools==11.2 was missing
All green!

**Comment by regebro** [comment]
Yeah, there is a deprecation warning triggered in later versions, I couldn't find an obvious way of going around that.

**Comment by regebro** [comment]
Oh, and I plan to set up a CLA and clahub.

**Pull request merged**
